SRC += jlw.c

NKRO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no